### PR TITLE
B2tweaks

### PR DESCRIPTION
**Pull request by hwine**
Prefer serving with livereloadx

It took me a while to figure livereloadx out, but it's really quite simple. No browser integration or source code changes are needed for "static mode" which works fine for learnjs style apps.

With these changes to the "server" function, all someone has to do to get live reload is install livereloadx per:
    http://nitoyon.github.io/livereloadx/

### CODE REVIEW

**Comment by benrady** [comment]
I'm a huge livereload fan. Slightly worried about changing the default behavior based on what you happen to have in your path, rather than an explicit command line option (like --livereload, or something like that).

**Comment by benrady** [comment]
What about a separate command? "liveserver" or something like that?

**Comment by benrady** [comment]
Thanks for the feedback. I added a separate command for this, which should now be available in the master branch.

**Comment by hwine** [comment]
great idea. Explicit is better than implicit.

**Pull request closed without merging**
